"""Main function ver0"""
import time
from coppeliasim_zmqremoteapi_client import RemoteAPIClient
import load
client = RemoteAPIClient()
sim = client.require('sim')
target_handle = sim.getObject('/UR5/target')
# cube_handle = sim.getObject('/Cuboid')
# cube_position = sim.getObjectPosition(cube_handle)
gripper_position = sim.getObjectPosition(target_handle)
time.sleep(3)
sim.startSimulation()
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 1)
# sim.setObjectPosition(target_handle, cube_position)
time.sleep(2)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 0)
time.sleep(5)
sim.setObjectPosition(target_handle, [0.3, -0.3, 0.5])
time.sleep(5)
# sim.setObjectPosition(target_handle, cube_position)
time.sleep(5)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 1)
time.sleep(5)
sim.setObjectPosition(target_handle, gripper_position)
time.sleep(5)
shape1_handle = load.load_shape(simulation=sim, shape_size=[
    0.05, 0.05, 0.05], shape_position=[0.2, 0.2, 0.5])
shape2_handle = load.load_shape(simulation=sim, shape_size=[
    0.05, 0.05, 0.05], shape_position=[0.4, 0.4, 0.4])
shape3_handle = load.load_shape(simulation=sim, shape_size=[
    0.05, 0.05, 0.05], shape_position=[0.3, 0.3, 0.4])
time.sleep(1)
shape1_position = sim.getObjectPosition(shape1_handle)
shape2_position = sim.getObjectPosition(shape2_handle)
shape3_position = sim.getObjectPosition(shape3_handle)
sim.setObjectPosition(target_handle, shape1_position)
time.sleep(1)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 0)
time.sleep(1)
sim.setObjectPosition(target_handle, gripper_position)
time.sleep(1)
sim.setObjectPosition(target_handle, [-0.2, 0.2, 0.05])
time.sleep(1)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 1)
time.sleep(1)
sim.setObjectPosition(target_handle, [0.4, 0.4, 0.4])
time.sleep(1)
sim.removeObjects([shape2_handle])
time.sleep(1)
sim.setObjectPosition(target_handle, shape3_position)
time.sleep(1)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 0)
time.sleep(1)
sim.setObjectPosition(target_handle, gripper_position)
time.sleep(1)
sim.setObjectPosition(target_handle, [-0.3, 0.3, 0.05])
time.sleep(1)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 1)
time.sleep(1)
sim.stopSimulation()
