"""Main function"""
import time
from coppeliasim_zmqremoteapi_client import RemoteAPIClient
import load
client = RemoteAPIClient()
sim = client.require('sim')
target_handle = sim.getObject('/UR5/target')
cube_handle = sim.getObject('/Cuboid')
# capsule_handle = sim.getObject('/Capsule')
cube_position = sim.getObjectPosition(cube_handle)
gripper_position = sim.getObjectPosition(target_handle)
# capsule_position = sim.getObjectPosition(capsule_handle)
time.sleep(3)
sim.startSimulation()
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 1)
sim.setObjectPosition(target_handle, cube_position)
# sim.setObjectPosition(target_handle, capsule_position)
time.sleep(2)
# sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 1)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 0)
time.sleep(5)
sim.setObjectPosition(target_handle, [0.3, -0.3, 0.5])
time.sleep(5)
sim.setObjectPosition(target_handle, cube_position)
# sim.setObjectPosition(target_handle, capsule_position)
time.sleep(5)
sim.setIntProperty(sim.handle_scene, 'signal.RG2_open', 1)
time.sleep(5)
sim.setObjectPosition(target_handle, gripper_position)
time.sleep(5)
load.load_shape(simulation=sim)
time.sleep(5)
sim.stopSimulation()
